# Generated by Django 4.2.6 on 2023-11-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='687944954259', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
