# Generated by Django 4.2.6 on 2023-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='570636298200', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
