# Generated by Django 4.2.6 on 2023-11-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версию', 'verbose_name_plural': 'Версии'},
        ),
    ]
